apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: release-book
  name: release-book-runtime
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-book-runtime
  strategy: {}
  template:
    metadata:
      labels:
        app: release-book-runtime
    spec:
      containers:
      - image: igoreulalio/release-book-architecture:v2.0.0
        imagePullPolicy: Always
        name: release-book-runtime
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000


